import { saveSiteSettingsAction } from "@/app/admin/actions";
import { AdminCard, AdminNotice, AdminPageHeader, Field, inputClass, textareaClass } from "@/components/admin/admin-ui";
import { cmsSelect } from "@/lib/cms/rest";
import { requireAdmin } from "@/lib/admin/session";

export default async function SiteSettingsPage({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  await requireAdmin(["owner", "admin"]);
  const [query, rows] = await Promise.all([searchParams, cmsSelect<Record<string, unknown>>("cms_site_settings", "select=*&limit=1")]);
  const settings = rows[0] ?? {};
  return <><AdminPageHeader eyebrow="Corporate" title="Site Settings" description="Store real company details here. Blank values stay blank on the public site rather than being fabricated." /><AdminNotice notice={query.notice} /><AdminCard><form action={saveSiteSettingsAction} className="grid gap-4 md:grid-cols-2"><Field label="Brand name"><input className={inputClass} name="company_name" defaultValue={String(settings.company_name ?? "KeyHold")} required /></Field><Field label="Legal name"><input className={inputClass} name="legal_name" defaultValue={String(settings.legal_name ?? "KeyHold")} required /></Field><Field label="Email"><input className={inputClass} type="email" name="email" defaultValue={String(settings.email ?? "hello@keyhold.ae")} required /></Field><Field label="Phone"><input className={inputClass} name="phone" defaultValue={String(settings.phone ?? "")} /></Field><Field label="Location"><input className={inputClass} name="location" defaultValue={String(settings.location ?? "Dubai, United Arab Emirates")} required /></Field><Field label="Office address"><input className={inputClass} name="address_line" defaultValue={String(settings.address_line ?? "")} /></Field><Field label="RERA ORN"><input className={inputClass} name="orn" defaultValue={String(settings.orn ?? "")} /></Field><Field label="Trade licence"><input className={inputClass} name="trade_license" defaultValue={String(settings.trade_license ?? "")} /></Field><Field label="Languages" hint="Comma separated"><input className={inputClass} name="languages" defaultValue={Array.isArray(settings.languages) ? settings.languages.join(", ") : "EN"} /></Field><div className="md:col-span-2"><Field label="Socials (JSON)"><textarea className={`${textareaClass} font-mono text-xs`} name="socials" defaultValue={JSON.stringify(settings.socials ?? [], null, 2)} /></Field></div><div className="md:col-span-2"><Field label="Google Reviews (JSON)" hint="Only enter real review data and a real profile URL."><textarea className={`${textareaClass} font-mono text-xs`} name="google_reviews" defaultValue={JSON.stringify(settings.google_reviews ?? { rating: null, reviewCount: null, href: "" }, null, 2)} /></Field></div><div className="md:col-span-2 text-right"><button className="button button-dark">Save settings</button></div></form></AdminCard></>;
}
