import { updateClientProfileAction } from "@/app/client-actions";
import { ClientCard } from "@/components/client/client-ui";
import { requireClientContext } from "@/lib/client/session";
import type { ClientLocale } from "@/types/client-portal";

export async function ClientProfilePage({ locale }: { locale: ClientLocale }) {
  const { user } = await requireClientContext(locale);
  return <div><h1 className="text-3xl font-semibold">{locale === "fr" ? "Profil" : "Profile"}</h1><ClientCard className="mt-6 max-w-2xl"><form action={updateClientProfileAction} className="grid gap-4"><input type="hidden" name="locale" value={locale}/><label className="grid gap-2 text-sm">{locale === "fr" ? "Nom complet" : "Full name"}<input name="fullName" defaultValue={user.fullName} className="min-h-11 rounded-xl border border-black/10 bg-white px-3"/></label><label className="grid gap-2 text-sm">Email<input value={user.email} readOnly className="min-h-11 rounded-xl border border-black/10 bg-[var(--color-warm-ivory)] px-3 text-[var(--color-stone)]"/></label><label className="grid gap-2 text-sm">{locale === "fr" ? "Téléphone" : "Phone"}<input name="phone" defaultValue={user.phone ?? ""} className="min-h-11 rounded-xl border border-black/10 bg-white px-3"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">{locale === "fr" ? "Langue préférée" : "Preferred language"}<select name="preferredLocale" defaultValue={user.preferredLocale} className="min-h-11 rounded-xl border border-black/10 bg-white px-3"><option value="en">English</option><option value="fr">Français</option></select></label><label className="grid gap-2 text-sm">{locale === "fr" ? "Devise" : "Currency"}<select name="preferredCurrency" defaultValue={user.preferredCurrency} className="min-h-11 rounded-xl border border-black/10 bg-white px-3">{["AED","USD","EUR","GBP","CHF"].map((c)=><option key={c}>{c}</option>)}</select></label></div><label className="flex items-start gap-3 text-sm"><input type="checkbox" name="marketingOptIn" defaultChecked={user.marketingOptIn} className="mt-1"/><span>{locale === "fr" ? "Recevoir les communications commerciales KeyHold." : "Receive KeyHold marketing communications."}</span></label><button type="submit" className="button button-dark w-fit">{locale === "fr" ? "Enregistrer" : "Save changes"}</button></form></ClientCard></div>;
}
