import { ClientCard, EmptyState } from "@/components/client/client-ui";
import { deleteWatchlistRuleAction } from "@/app/client-actions";
import { requireClientContext } from "@/lib/client/session";
import { getClientSavedProjects, getClientWatchlistRules } from "@/lib/client/queries";
import type { ClientLocale } from "@/types/client-portal";
import { clientEnumLabel } from "@/lib/client/locale";
import { createWatchlistRuleAction } from "@/app/client-actions";

export async function ClientWatchlistPage({ locale }: { locale: ClientLocale }) {
  const { accessToken } = await requireClientContext(locale);
  const [rules, saved] = await Promise.all([getClientWatchlistRules(accessToken), getClientSavedProjects(accessToken, locale, 50)]);
  return <div className="grid gap-6"><div><h1 className="text-3xl font-semibold">{locale === "fr" ? "Veille" : "Watchlist"}</h1><p className="mt-3 text-sm leading-7 text-[var(--color-stone)]">{locale === "fr" ? "Créez des règles de veille in-app. L'envoi email sera activé séparément lorsqu'un service d'email transactionnel sera configuré." : "Create in-app watch rules. Email delivery will be enabled separately when a transactional email service is configured."}</p></div><ClientCard><h2 className="text-lg font-semibold">{locale === "fr" ? "Nouvelle règle" : "New rule"}</h2>{saved.length ? <form action={createWatchlistRuleAction} className="mt-4 grid gap-3 md:grid-cols-3"><input type="hidden" name="locale" value={locale}/><label className="grid gap-1 text-sm">{locale === "fr" ? "Projet" : "Project"}<select name="projectId" className="min-h-11 rounded-xl border border-black/10 bg-white px-3">{saved.map((p)=><option key={p.projectId} value={p.projectId}>{p.title}</option>)}</select></label><label className="grid gap-1 text-sm">{locale === "fr" ? "Alerte" : "Alert"}<select name="ruleType" className="min-h-11 rounded-xl border border-black/10 bg-white px-3"><option value="price-below">{locale === "fr" ? "Prix sous" : "Price below"}</option><option value="construction-reaches">{locale === "fr" ? "Construction atteint" : "Construction reaches"}</option><option value="new-unit">{locale === "fr" ? "Nouvelle unité" : "New unit"}</option></select></label><label className="grid gap-1 text-sm">{locale === "fr" ? "Seuil si nécessaire" : "Threshold if needed"}<input name="threshold" inputMode="decimal" className="min-h-11 rounded-xl border border-black/10 bg-white px-3" placeholder="e.g. 80"/></label><button className="button button-dark md:col-span-3 md:w-fit" type="submit">{locale === "fr" ? "Ajouter" : "Add rule"}</button></form> : <p className="mt-3 text-sm text-[var(--color-stone)]">{locale === "fr" ? "Enregistrez d'abord un projet." : "Save a project first."}</p>}</ClientCard>{rules.length ? <div className="grid gap-3">{rules.map((r)=><ClientCard key={r.id} className="p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-medium">{clientEnumLabel(locale, r.ruleType)}</p><p className="mt-1 text-xs text-[var(--color-stone)]">{r.thresholdNumeric ?? "—"} · {clientEnumLabel(locale, r.isActive ? "active" : "paused")}</p></div><form action={deleteWatchlistRuleAction}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="id" value={r.id}/><button className="text-sm text-[var(--color-terracotta)]" type="submit">{locale === "fr" ? "Supprimer" : "Delete"}</button></form></div></ClientCard>)}</div> : <EmptyState title={locale === "fr" ? "Aucune règle" : "No watch rules"} text={locale === "fr" ? "Vos règles de suivi apparaîtront ici." : "Your monitoring rules will appear here."}/>}</div>;
}
