import { deleteTranslationAction, saveTranslationAction } from "@/app/admin/localization-actions";
import { AdminCard, AdminNotice, AdminPageHeader, Field, inputClass, selectClass, textareaClass } from "@/components/admin/admin-ui";
import { requireAdmin } from "@/lib/admin/session";
import { cmsSelect } from "@/lib/cms/rest";

const entityTypes = ["website-settings","website-page","website-section","navigation-item","person","testimonial","faq","form","project","developer","area","unit","payment-milestone","floor-plan","document","construction-update","intelligence-profile","intelligence-source","insight","service"] as const;
type TranslationRow = { id:string; entity_type:string; entity_key:string; locale:string; status:string; data:Record<string,unknown>; updated_at:string };

function TranslationForm({ item }: { item?: TranslationRow }) {
  return <form action={saveTranslationAction} className="grid gap-4 md:grid-cols-2">{item?<input type="hidden" name="id" value={item.id}/>:null}<Field label="Content type"><select className={selectClass} name="entity_type" defaultValue={item?.entity_type ?? "project"}>{entityTypes.map((type)=><option key={type} value={type}>{type}</option>)}</select></Field><Field label="Content key" hint="Stable key such as project slug, page key, or navigation group:/href."><input className={inputClass} name="entity_key" defaultValue={item?.entity_key ?? ""} required /></Field><Field label="Language"><select className={selectClass} name="locale" defaultValue={item?.locale ?? "fr"}><option value="fr">Français (fr)</option></select></Field><Field label="Status"><select className={selectClass} name="status" defaultValue={item?.status ?? "draft"}><option value="draft">Draft translation</option><option value="published">Published translation</option></select></Field><div className="md:col-span-2"><Field label="Translated fields" hint="This advanced fallback editor stores only translated fields. Claude must also add friendly EN/FR fields to normal content editors for daily use."><textarea className={`${textareaClass} min-h-64 font-mono text-xs`} name="data" defaultValue={JSON.stringify(item?.data ?? {},null,2)} required /></Field></div><div className="md:col-span-2 flex justify-end gap-2">{item?<button className="button border border-black/10" formAction={deleteTranslationAction} name="id" value={item.id} formNoValidate>Delete</button>:null}<button className="button button-dark">Save translation</button></div></form>;
}

export default async function WebsiteTranslationsPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  await requireAdmin();
  const [query, rows] = await Promise.all([searchParams, cmsSelect<TranslationRow>("cms_translations", "select=*&order=entity_type.asc,entity_key.asc,locale.asc")]);
  return <><AdminPageHeader eyebrow="Website manager" title="Translations" description="Central EN/FR translation ledger. English is the canonical content. French records override only the fields you translate; missing French fields safely fall back to English."/><AdminNotice notice={query.notice} error={query.error}/><AdminCard eyebrow="Important" title="Daily editing should stay simple"><p className="text-sm leading-7 text-[var(--color-stone)]">Claude must surface French fields next to English inside Projects, Developers, Areas, Updates, Intelligence, Insights, Services and Website Studio. This page remains the advanced ledger and recovery editor.</p></AdminCard><div className="mt-6 grid gap-4">{rows.map((row)=><AdminCard key={row.id} eyebrow={`${row.locale} · ${row.status}`} title={`${row.entity_type} · ${row.entity_key}`}><details><summary className="cursor-pointer text-sm font-semibold">Edit translation</summary><div className="mt-5 border-t border-black/10 pt-5"><TranslationForm item={row}/></div></details></AdminCard>)}<AdminCard eyebrow="Translation" title="Add translation"><TranslationForm/></AdminCard></div></>;
}
