import { deleteGlobalMediaAction, uploadGlobalMediaAction } from "@/app/admin/website-actions";
import { AdminCard, AdminNotice, AdminPageHeader, Field, inputClass, selectClass } from "@/components/admin/admin-ui";
import { requireAdmin } from "@/lib/admin/session";
import { cmsSelect } from "@/lib/cms/rest";

type MediaRow = { id:string; label:string; kind:string; bucket:string; storage_path:string; public_url:string; alt_text:string; tags:string[]; created_at:string };

export default async function MediaAdmin({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  await requireAdmin();
  const [query, media] = await Promise.all([searchParams, cmsSelect<MediaRow>("cms_media_library", "select=*&order=created_at.desc")]);
  return <><AdminPageHeader eyebrow="Website manager" title="Media Library" description="Upload reusable public assets once, then paste their URL into any hero, section, team member, testimonial or global brand field."/><AdminNotice notice={query.notice} error={query.error}/><AdminCard eyebrow="Upload" title="Add website media"><form action={uploadGlobalMediaAction} className="grid gap-4 md:grid-cols-2"><Field label="Label"><input className={inputClass} name="label" required/></Field><Field label="Kind"><select className={selectClass} name="kind" defaultValue="image"><option value="image">Image</option><option value="video">Video</option><option value="logo">Logo</option><option value="icon">Icon</option><option value="document">Public document</option></select></Field><Field label="File"><input className={inputClass} type="file" name="file" required/></Field><Field label="Alt text"><input className={inputClass} name="alt_text"/></Field><div className="md:col-span-2"><Field label="Tags" hint="Comma separated"><input className={inputClass} name="tags"/></Field></div><div className="md:col-span-2 text-right"><button className="button button-dark">Upload media</button></div></form></AdminCard><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{media.map((item)=><AdminCard key={item.id} eyebrow={item.kind} title={item.label}><div className="grid gap-3 text-sm"><p className="break-all text-xs text-[var(--color-stone)]">{item.public_url}</p>{item.alt_text?<p>{item.alt_text}</p>:null}{item.tags?.length?<p className="text-xs text-[var(--color-stone)]">{item.tags.join(" · ")}</p>:null}<a href={item.public_url} target="_blank" rel="noreferrer" className="text-link">Open asset ↗</a><form action={deleteGlobalMediaAction}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="bucket" value={item.bucket}/><input type="hidden" name="storage_path" value={item.storage_path}/><button className="button border border-black/10 text-xs">Delete</button></form></div></AdminCard>)}</div></>;
}
