import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/session";
import { cmsSelect } from "@/lib/cms/rest";
import { addClientAdvisorNoteAction, addClientNotificationAction, addClientPaymentAction, addClientPortfolioAssetAction, assignClientAdvisorAction, setClientStatusAction, uploadClientDocumentAction } from "@/app/admin/client-actions";

export const metadata = { robots: { index: false, follow: false } };

type Profile = { user_id: string; email: string; full_name: string; phone: string | null; status: string; preferred_locale: string; preferred_currency: string; advisor_user_id: string | null; created_at: string };
type Admin = { user_id: string; role: string; is_active: boolean };
type Asset = { id: string; custom_title: string | null; ownership_status: string; purchase_price_aed: number; paid_to_date_aed: number; project_id: string | null; unit_id: string | null };

function Field({ label, name, type="text", required=false }: { label:string;name:string;type?:string;required?:boolean }) { return <label className="grid gap-1 text-sm">{label}<input className="min-h-11 rounded-xl border border-black/10 bg-white px-3" name={name} type={type} required={required}/></label>; }
function Panel({ title, children }: { title:string; children:React.ReactNode }) { return <section className="rounded-[24px] border border-black/8 bg-[var(--color-soft-white)] p-5"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-4">{children}</div></section>; }

export default async function ClientAdminDetailPage({ params }: { params: Promise<{ userId: string }> }) {
  await requireAdmin();
  const { userId } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(userId)) notFound();
  const [profiles, admins, assets] = await Promise.all([
    cmsSelect<Profile>("client_profiles", `select=user_id,email,full_name,phone,status,preferred_locale,preferred_currency,advisor_user_id,created_at&user_id=eq.${userId}&limit=1`),
    cmsSelect<Admin>("admin_profiles", "select=user_id,role,is_active&is_active=eq.true"),
    cmsSelect<Asset>("client_portfolio_assets", `select=id,custom_title,ownership_status,purchase_price_aed,paid_to_date_aed,project_id,unit_id&user_id=eq.${userId}&order=created_at.desc`),
  ]);
  const profile=profiles[0]; if(!profile) notFound();
  return <div className="grid gap-6"><div><p className="text-xs uppercase tracking-[0.18em] text-[var(--color-teal)]">Client file</p><h1 className="mt-2 text-3xl font-semibold">{profile.full_name || profile.email}</h1><p className="mt-2 text-sm text-[var(--color-stone)]">{profile.email} · {profile.preferred_locale.toUpperCase()} · {profile.preferred_currency}</p></div><div className="grid gap-5 xl:grid-cols-2">
    <Panel title="Access & advisor"><form action={setClientStatusAction} className="grid gap-3"><input type="hidden" name="userId" value={userId}/><select name="status" defaultValue={profile.status} className="min-h-11 rounded-xl border border-black/10 bg-white px-3"><option value="active">Active</option><option value="blocked">Blocked</option></select><button className="button button-light w-fit" type="submit">Update status</button></form><form action={assignClientAdvisorAction} className="mt-5 grid gap-3"><input type="hidden" name="userId" value={userId}/><select name="advisorUserId" defaultValue={profile.advisor_user_id ?? ""} className="min-h-11 rounded-xl border border-black/10 bg-white px-3"><option value="">No advisor</option>{admins.map((a)=><option key={a.user_id} value={a.user_id}>{a.role} · {a.user_id.slice(0,8)}</option>)}</select><button className="button button-light w-fit" type="submit">Assign advisor</button></form></Panel>
    <Panel title="Add portfolio asset"><form action={addClientPortfolioAssetAction} className="grid gap-3"><input type="hidden" name="userId" value={userId}/><Field label="Project UUID (optional)" name="projectId"/><Field label="Unit UUID (optional)" name="unitId"/><Field label="Custom title" name="customTitle"/><label className="grid gap-1 text-sm">Status<select name="ownershipStatus" className="min-h-11 rounded-xl border border-black/10 bg-white px-3">{["reserved","contracted","under-construction","handed-over","rented","sold"].map(s=><option key={s}>{s}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><Field label="Purchase price AED" name="purchasePriceAed" type="number" required/><Field label="Paid to date AED" name="paidToDateAed" type="number"/></div><Field label="Estimated value AED" name="estimatedValueAed" type="number"/><Field label="Acquisition date" name="acquisitionDate" type="date"/><button className="button button-dark w-fit" type="submit">Add asset</button></form></Panel>
    <Panel title="Payment item"><form action={addClientPaymentAction} className="grid gap-3"><input type="hidden" name="userId" value={userId}/><label className="grid gap-1 text-sm">Asset<select name="assetId" className="min-h-11 rounded-xl border border-black/10 bg-white px-3">{assets.map(a=><option key={a.id} value={a.id}>{a.custom_title || a.id.slice(0,8)} · {a.ownership_status}</option>)}</select></label><Field label="Label" name="label" required/><Field label="Due date" name="dueDate" type="date" required/><Field label="Amount AED" name="amountAed" type="number" required/><label className="grid gap-1 text-sm">Status<select name="status" className="min-h-11 rounded-xl border border-black/10 bg-white px-3"><option>upcoming</option><option>due</option><option>paid</option><option>overdue</option><option>waived</option></select></label><button className="button button-dark w-fit" type="submit">Add payment</button></form></Panel>
    <Panel title="Private document"><form action={uploadClientDocumentAction} className="grid gap-3"><input type="hidden" name="userId" value={userId}/><label className="grid gap-1 text-sm">Asset<select name="assetId" className="min-h-11 rounded-xl border border-black/10 bg-white px-3"><option value="">General client file</option>{assets.map(a=><option key={a.id} value={a.id}>{a.custom_title || a.id.slice(0,8)}</option>)}</select></label><Field label="Document label" name="label"/><label className="grid gap-1 text-sm">Category<select name="category" className="min-h-11 rounded-xl border border-black/10 bg-white px-3">{["Reservation","KYC","SPA","Receipt","DLD","Handover","Inspection","Other"].map(s=><option key={s}>{s}</option>)}</select></label><input name="file" type="file" required className="text-sm"/><button className="button button-dark w-fit" type="submit">Upload privately</button></form></Panel>
    <Panel title="Advisor note"><form action={addClientAdvisorNoteAction} className="grid gap-3"><input type="hidden" name="userId" value={userId}/><textarea name="body" rows={5} required className="rounded-xl border border-black/10 bg-white p-3"/><label className="flex gap-2 text-sm"><input type="checkbox" name="isPinned"/>Pinned</label><input type="hidden" name="visibleToClient" value="on"/><button className="button button-dark w-fit" type="submit">Add visible note</button></form></Panel>
    <Panel title="Notification"><form action={addClientNotificationAction} className="grid gap-3"><input type="hidden" name="userId" value={userId}/><label className="grid gap-1 text-sm">Kind<select name="kind" className="min-h-11 rounded-xl border border-black/10 bg-white px-3">{["update","payment","document","advisor","watchlist","system"].map(s=><option key={s}>{s}</option>)}</select></label><Field label="Title" name="title" required/><textarea name="body" rows={3} required className="rounded-xl border border-black/10 bg-white p-3"/><Field label="Link (optional)" name="href"/><label className="grid gap-1 text-sm">Severity<select name="severity" className="min-h-11 rounded-xl border border-black/10 bg-white px-3"><option>info</option><option>positive</option><option>warning</option></select></label><button className="button button-dark w-fit" type="submit">Send in-app</button></form></Panel>
  </div></div>;
}
